run-name: Build and upload CD artifacts
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: build shorty
    - uses: actions/checkout@v4
    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
    - run: cd src/Shorty && dotnet publish -r linux-arm64 /p:PublishSingleFile=true /p:SelfContained=true -o output
    - name: upload output
    - uses: actions/upload-artifact@v4
      with:
        name: shorty-latest
        path: src/Shorty/output
        if-no-files-found: fail
        overwrite: true
